#SPRING CONFIGURATION
spring:
  application:
    name: HouseService
  datasource:
    url: jdbc:postgresql://localhost:5432/houses
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 87654321
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
#SERVER
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always