spring:
  datasource:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/carpark
      username: postgres
      password: 87654321
cache:
  capacity: 3
  algorithm: LFUCache