CREATE TABLE IF NOT EXISTS persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    sex VARCHAR(10)
    passport_series VARCHAR(50) NOT NULL,
    passport_number VARCHAR(50) NOT NULL,
    create_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP NOT NULL,
    house_id BIGINT
);

ALTER TABLE persons
 ADD CONSTRAINT fk_persons_house FOREIGN KEY (house_id) REFERENCES houses(id);